### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by dmitrika** [erikras/final-form#6]
### Are you submitting a **bug report** or a **feature request**?
Documentation feature request

### Other information

Thanks for redux form, it's super lib. It's not easy to start with, but examples make dx much better. So, it would be cool, to implement at least all basic cases with final-form as well. Any plans about it? Can contributors just create examples dir or any other way to help?

**Comment by erikras** [comment]
The thing is that `final-form` doesn't really _do_ much without a view layer on top. I'm not sure what a `final-form` example would look like.

The best examples are here: [React Final Form Examples](https://github.com/erikras/react-final-form#examples)

**Comment by dmitrika** [comment]
Aha, got the point! Didn't know about react final form repo before.

**Comment by erikras** [comment]
Nevertheless, your confusion highlighted a communication problem on my side. So I made [an example](https://github.com/erikras/final-form#examples)!

**Comment by erikras** [comment]
Published in [`v1.1.0`](https://github.com/erikras/final-form/releases/tag/v1.1.0).
